apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backstage-project-api
  description: API documentation for My Node.js Service
  annotations:
    backstage.io/depends-on: 'component:backstage-project'
spec:
  type: openapi
  lifecycle: production
  owner: SunLight67-hub
  system: Backstage-Project
  definition:
    $text: 'https://backstage-project.onrender.com/docs'
