apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-project
  description: A sample Node.js service with Swagger API documentation
  tags:
    - nodejs
    - api
    - swagger
  annotations:
    github.com/project-slug: SunLight67-hub/backstage-project
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: SunLight67-hub
  system: Backstage-Project
  doc_links: https://docs.google.com/document/d/1thDOiqztvot7YzGUTe4p4M7qdlA0BQp14w3acstKyY8/edit?tab=t.0
  providesApis:
    - backstage-project-api  # Links to the API this component provides
